/**
 * Taxonomie STEM (Science, Technologie, Ingenierie, Mathematiques) : pour chaque domaine,
 * la liste des metiers/disciplines (affiches aux mentees) et leur appellation feminine
 * de professionnelle correspondante (affichee aux mentores). Liste non exhaustive fournie
 * par STF (document Liste non exhaustive metiers STEM au feminin).
 */
export type StemDomain = "science" | "technologie" | "ingenierie" | "mathematiques";

export type StemFieldEntry = {
  /** Discipline ou specialite - proposee aux mentees. */
  metier: string;
  /** Appellation feminine de la professionnelle - proposee aux mentores. */
  profession: string;
};

export const stemDomains: StemDomain[] = ["science", "technologie", "ingenierie", "mathematiques"];

export const stemDomainLabels: Record<StemDomain, string> = {
  science: "Science",
  technologie: "Technologie",
  ingenierie: "Ingénierie",
  mathematiques: "Mathématiques",
};

export const stemFields: Record<StemDomain, StemFieldEntry[]> = {
  science: [
    { metier: "Biologie", profession: "Biologiste" },
    { metier: "Biologie animale", profession: "Biologiste animale" },
    { metier: "Biologie végétale", profession: "Biologiste végétale" },
    { metier: "Biologie cellulaire", profession: "Biologiste cellulaire" },
    { metier: "Biologie moléculaire", profession: "Biologiste moléculaire" },
    { metier: "Biologie structurale", profession: "Biologiste structurale" },
    { metier: "Biologie marine", profession: "Biologiste marine" },
    { metier: "Biologie de la conservation", profession: "Biologiste de la conservation" },
    { metier: "Biologie computationnelle", profession: "Biologiste computationnelle" },
    { metier: "Microbiologie", profession: "Microbiologiste" },
    { metier: "Bactériologie", profession: "Bactériologiste" },
    { metier: "Virologie", profession: "Virologue" },
    { metier: "Mycologie", profession: "Mycologue" },
    { metier: "Parasitologie", profession: "Parasitologue" },
    { metier: "Immunologie", profession: "Immunologiste" },
    { metier: "Génétique", profession: "Généticienne" },
    { metier: "Génomique", profession: "Spécialiste en génomique" },
    { metier: "Protéomique", profession: "Spécialiste en protéomique" },
    { metier: "Biochimie", profession: "Biochimiste" },
    { metier: "Biophysique", profession: "Biophysicienne" },
    { metier: "Biotechnologie", profession: "Biotechnologiste" },
    { metier: "Bio-informatique", profession: "Bio-informaticienne" },
    { metier: "Neurosciences", profession: "Neuroscientifique" },
    { metier: "Neurobiologie", profession: "Neurobiologiste" },
    { metier: "Anatomie", profession: "Anatomiste" },
    { metier: "Physiologie", profession: "Physiologiste" },
    { metier: "Embryologie", profession: "Embryologiste" },
    { metier: "Histologie", profession: "Histologiste" },
    { metier: "Pathologie", profession: "Anatomopathologiste ou pathologiste" },
    { metier: "Pharmacologie", profession: "Pharmacologue" },
    { metier: "Toxicologie", profession: "Toxicologue" },
    { metier: "Épidémiologie", profession: "Épidémiologiste" },
    { metier: "Santé publique", profession: "Spécialiste en santé publique" },
    { metier: "Sciences biomédicales", profession: "Scientifique biomédicale" },
    { metier: "Recherche clinique", profession: "Chercheuse clinique" },
    { metier: "Sciences pharmaceutiques", profession: "Chercheuse en sciences pharmaceutiques" },
    { metier: "Chimie", profession: "Chimiste" },
    { metier: "Chimie analytique", profession: "Chimiste analyste" },
    { metier: "Chimie organique", profession: "Chimiste organicienne" },
    { metier: "Chimie inorganique", profession: "Chimiste inorganicienne" },
    { metier: "Chimie physique", profession: "Chimiste physicienne" },
    { metier: "Chimie industrielle", profession: "Chimiste industrielle" },
    { metier: "Chimie environnementale", profession: "Chimiste environnementale" },
    { metier: "Électrochimie", profession: "Électrochimiste" },
    { metier: "Radiochimie", profession: "Radiochimiste" },
    { metier: "Science des matériaux", profession: "Scientifique des matériaux" },
    { metier: "Physique", profession: "Physicienne" },
    { metier: "Physique appliquée", profession: "Physicienne en physique appliquée" },
    { metier: "Physique théorique", profession: "Physicienne théoricienne" },
    { metier: "Physique expérimentale", profession: "Physicienne expérimentatrice" },
    { metier: "Physique quantique", profession: "Physicienne quantique" },
    { metier: "Physique nucléaire", profession: "Physicienne nucléaire" },
    { metier: "Physique des particules", profession: "Physicienne des particules" },
    { metier: "Physique de la matière condensée", profession: "Physicienne de la matière condensée" },
    { metier: "Optique", profession: "Opticienne scientifique ou physicienne opticienne" },
    { metier: "Photonique", profession: "Spécialiste en photonique" },
    { metier: "Acoustique", profession: "Acousticienne" },
    { metier: "Astronomie", profession: "Astronome" },
    { metier: "Astrophysique", profession: "Astrophysicienne" },
    { metier: "Cosmologie", profession: "Cosmologiste" },
    { metier: "Planétologie", profession: "Planétologue" },
    { metier: "Sciences spatiales", profession: "Scientifique spatiale" },
    { metier: "Géologie", profession: "Géologue" },
    { metier: "Géophysique", profession: "Géophysicienne" },
    { metier: "Géochimie", profession: "Géochimiste" },
    { metier: "Minéralogie", profession: "Minéralogiste" },
    { metier: "Pétrologie", profession: "Pétrologue" },
    { metier: "Sismologie", profession: "Sismologue" },
    { metier: "Volcanologie", profession: "Volcanologue" },
    { metier: "Paléontologie", profession: "Paléontologue" },
    { metier: "Hydrologie", profession: "Hydrologue" },
    { metier: "Hydrogéologie", profession: "Hydrogéologue" },
    { metier: "Limnologie", profession: "Limnologue" },
    { metier: "Océanographie", profession: "Océanographe" },
    { metier: "Météorologie", profession: "Météorologue" },
    { metier: "Climatologie", profession: "Climatologue" },
    { metier: "Sciences de l’atmosphère", profession: "Scientifique de l’atmosphère" },
    { metier: "Sciences du climat", profession: "Scientifique du climat" },
    { metier: "Glaciologie", profession: "Glaciologue" },
    { metier: "Géographie physique", profession: "Géographe physicienne" },
    { metier: "Écologie", profession: "Écologue" },
    { metier: "Écotoxicologie", profession: "Écotoxicologue" },
    { metier: "Sciences de l’environnement", profession: "Environnementaliste ou scientifique de l’environnement" },
    { metier: "Botanique", profession: "Botaniste" },
    { metier: "Zoologie", profession: "Zoologiste" },
    { metier: "Entomologie", profession: "Entomologiste" },
    { metier: "Ornithologie", profession: "Ornithologue" },
    { metier: "Ichtyologie", profession: "Ichtyologue" },
    { metier: "Primatologie", profession: "Primatologue" },
    { metier: "Éthologie", profession: "Éthologue" },
    { metier: "Taxonomie", profession: "Taxonomiste" },
    { metier: "Biodiversité", profession: "Spécialiste de la biodiversité" },
    { metier: "Conservation de la nature", profession: "Spécialiste en conservation de la nature" },
    { metier: "Agronomie", profession: "Agronome" },
    { metier: "Agroécologie", profession: "Agroécologue" },
    { metier: "Pédologie", profession: "Pédologue" },
    { metier: "Sciences du sol", profession: "Scientifique du sol" },
    { metier: "Phytopathologie", profession: "Phytopathologiste" },
    { metier: "Sciences forestières", profession: "Scientifique forestière" },
    { metier: "Sciences alimentaires", profession: "Scientifique des aliments" },
    { metier: "Nutrition", profession: "Nutritionniste" },
    { metier: "Archéologie scientifique", profession: "Archéologue" },
    { metier: "Anthropologie biologique", profession: "Anthropologue biologiste" },
    { metier: "Science forensique", profession: "Scientifique forensique" },
    { metier: "Analyse de laboratoire", profession: "Analyste de laboratoire" },
    { metier: "Technique de laboratoire", profession: "Technicienne de laboratoire" },
    { metier: "Recherche scientifique", profession: "Chercheuse" },
    { metier: "Enseignement des sciences", profession: "Enseignante de sciences" },
    { metier: "Médiation scientifique", profession: "Médiatrice scientifique" },
    { metier: "Communication scientifique", profession: "Communicatrice scientifique" },
  ],
  technologie: [
    { metier: "Informatique", profession: "Informaticienne" },
    { metier: "Développement informatique", profession: "Développeuse informatique" },
    { metier: "Programmation", profession: "Programmeuse" },
    { metier: "Développement web", profession: "Développeuse web" },
    { metier: "Développement front-end", profession: "Développeuse front-end" },
    { metier: "Développement back-end", profession: "Développeuse back-end" },
    { metier: "Développement full-stack", profession: "Développeuse full-stack" },
    { metier: "Développement mobile", profession: "Développeuse d’applications mobiles" },
    { metier: "Développement de logiciels", profession: "Développeuse de logiciels" },
    { metier: "Génie logiciel", profession: "Ingénieure en génie logiciel" },
    { metier: "Architecture logicielle", profession: "Architecte logicielle" },
    { metier: "Analyse fonctionnelle", profession: "Analyste fonctionnelle" },
    { metier: "Analyse des systèmes", profession: "Analyste de systèmes" },
    { metier: "Administration de systèmes", profession: "Administratrice de systèmes" },
    { metier: "Administration de réseaux", profession: "Administratrice de réseaux" },
    { metier: "Administration de bases de données", profession: "Administratrice de bases de données" },
    { metier: "Réseaux informatiques", profession: "Spécialiste en réseaux informatiques" },
    { metier: "Télécommunications", profession: "Ingénieure ou spécialiste en télécommunications" },
    { metier: "Infrastructure informatique", profession: "Ingénieure d’infrastructure informatique" },
    { metier: "Cloud computing", profession: "Ingénieure cloud" },
    { metier: "Architecture cloud", profession: "Architecte cloud" },
    { metier: "Administration cloud", profession: "Administratrice cloud" },
    { metier: "DevOps", profession: "Ingénieure DevOps" },
    { metier: "Site Reliability Engineering", profession: "Ingénieure en fiabilité des sites" },
    { metier: "Cybersécurité", profession: "Spécialiste en cybersécurité" },
    { metier: "Sécurité informatique", profession: "Analyste en sécurité informatique" },
    { metier: "Sécurité des réseaux", profession: "Ingénieure en sécurité des réseaux" },
    { metier: "Sécurité des applications", profession: "Ingénieure en sécurité applicative" },
    { metier: "Tests d’intrusion", profession: "Testeuse d’intrusion ou auditrice en cybersécurité" },
    { metier: "Cryptographie appliquée", profession: "Cryptographe appliquée" },
    { metier: "Audit informatique", profession: "Auditrice informatique" },
    { metier: "Gouvernance informatique", profession: "Spécialiste en gouvernance informatique" },
    { metier: "Protection des données", profession: "Déléguée à la protection des données" },
    { metier: "Forensique numérique", profession: "Analyste en investigation numérique" },
    { metier: "Tests logiciels", profession: "Testeuse de logiciels" },
    { metier: "Assurance qualité logicielle", profession: "Ingénieure qualité logiciel" },
    { metier: "Automatisation des tests", profession: "Ingénieure en automatisation des tests" },
    { metier: "Maintenance informatique", profession: "Technicienne en maintenance informatique" },
    { metier: "Support informatique", profession: "Technicienne de support informatique" },
    { metier: "Assistance aux utilisatrices et utilisateurs", profession: "Technicienne d’assistance informatique" },
    { metier: "Science des données", profession: "Scientifique des données" },
    { metier: "Analyse de données", profession: "Analyste de données" },
    { metier: "Ingénierie des données", profession: "Ingénieure des données" },
    { metier: "Architecture des données", profession: "Architecte des données" },
    { metier: "Administration des données", profession: "Administratrice des données" },
    { metier: "Gouvernance des données", profession: "Spécialiste en gouvernance des données" },
    { metier: "Qualité des données", profession: "Analyste de la qualité des données" },
    { metier: "Visualisation de données", profession: "Spécialiste en visualisation de données" },
    { metier: "Informatique décisionnelle", profession: "Analyste en informatique décisionnelle" },
    { metier: "Intelligence artificielle", profession: "Spécialiste en intelligence artificielle" },
    { metier: "Apprentissage automatique", profession: "Ingénieure en apprentissage automatique" },
    { metier: "Apprentissage profond", profession: "Spécialiste en apprentissage profond" },
    { metier: "Traitement automatique du langage", profession: "Ingénieure en traitement automatique du langage" },
    { metier: "Vision par ordinateur", profession: "Ingénieure en vision par ordinateur" },
    { metier: "IA générative", profession: "Spécialiste en intelligence artificielle générative" },
    { metier: "MLOps", profession: "Ingénieure MLOps" },
    { metier: "Robotique", profession: "Roboticienne" },
    { metier: "Automatisation", profession: "Spécialiste en automatisation" },
    { metier: "Systèmes embarqués", profession: "Ingénieure en systèmes embarqués" },
    { metier: "Internet des objets", profession: "Spécialiste de l’Internet des objets" },
    { metier: "Informatique industrielle", profession: "Informaticienne industrielle" },
    { metier: "Blockchain", profession: "Développeuse ou spécialiste blockchain" },
    { metier: "Technologies financières", profession: "Spécialiste en technologies financières" },
    { metier: "Réalité virtuelle", profession: "Développeuse en réalité virtuelle" },
    { metier: "Réalité augmentée", profession: "Développeuse en réalité augmentée" },
    { metier: "Réalité mixte", profession: "Développeuse en réalité mixte" },
    { metier: "Jeux vidéo", profession: "Développeuse de jeux vidéo" },
    { metier: "Conception de jeux", profession: "Conceptrice de jeux vidéo" },
    { metier: "Animation numérique", profession: "Animatrice numérique" },
    { metier: "Animation 2D et 3D", profession: "Animatrice 2D et 3D" },
    { metier: "Modélisation 3D", profession: "Modélisatrice 3D" },
    { metier: "Infographie", profession: "Infographiste" },
    { metier: "Design numérique", profession: "Designeuse numérique" },
    { metier: "Conception UX", profession: "Conceptrice UX" },
    { metier: "Conception UI", profession: "Conceptrice UI" },
    { metier: "Design d’interaction", profession: "Designeuse d’interaction" },
    { metier: "Accessibilité numérique", profession: "Experte en accessibilité numérique" },
    { metier: "Gestion de produits numériques", profession: "Cheffe de produit numérique" },
    { metier: "Gestion de projets informatiques", profession: "Cheffe de projet informatique" },
    { metier: "Scrum", profession: "Scrum master" },
    { metier: "Transformation numérique", profession: "Consultante en transformation numérique" },
    { metier: "Conseil informatique", profession: "Consultante informatique" },
    { metier: "Architecture des systèmes d’information", profession: "Architecte des systèmes d’information" },
    { metier: "Urbanisation des systèmes d’information", profession: "Urbaniste des systèmes d’information" },
    { metier: "Gestion des services informatiques", profession: "Gestionnaire de services informatiques" },
    { metier: "Géomatique", profession: "Géomaticienne" },
    { metier: "Systèmes d’information géographique", profession: "Spécialiste en systèmes d’information géographique" },
    { metier: "Cartographie numérique", profession: "Cartographe numérique" },
    { metier: "Télédétection", profession: "Spécialiste en télédétection" },
    { metier: "Bio-informatique", profession: "Bio-informaticienne" },
    { metier: "Informatique médicale", profession: "Spécialiste en informatique médicale" },
    { metier: "Informatique de santé", profession: "Informaticienne de santé" },
    { metier: "Technologies éducatives", profession: "Spécialiste en technologies éducatives" },
    { metier: "Technologies agricoles", profession: "Spécialiste en technologies agricoles" },
    { metier: "Technologies climatiques", profession: "Spécialiste en technologies climatiques" },
    { metier: "Drones", profession: "Pilote ou technicienne de drones" },
    { metier: "Fabrication numérique", profession: "Spécialiste en fabrication numérique" },
    { metier: "Impression 3D", profession: "Technicienne en impression 3D" },
    { metier: "Maintenance électronique", profession: "Technicienne en maintenance électronique" },
    { metier: "Audiovisuel numérique", profession: "Technicienne audiovisuelle" },
    { metier: "Production multimédia", profession: "Productrice multimédia" },
    { metier: "Enseignement de l’informatique", profession: "Enseignante d’informatique" },
    { metier: "Formation numérique", profession: "Formatrice en numérique" },
    { metier: "Recherche technologique", profession: "Chercheuse en technologie" },
  ],
  ingenierie: [
    { metier: "Génie civil", profession: "Ingénieure en génie civil" },
    { metier: "Construction", profession: "Ingénieure en construction" },
    { metier: "Bâtiment", profession: "Ingénieure en bâtiment" },
    { metier: "Travaux publics", profession: "Ingénieure en travaux publics" },
    { metier: "Structures", profession: "Ingénieure en structures" },
    { metier: "Ouvrages d’art", profession: "Ingénieure en ouvrages d’art" },
    { metier: "Routes", profession: "Ingénieure routière" },
    { metier: "Ponts et chaussées", profession: "Ingénieure des ponts et chaussées" },
    { metier: "Géotechnique", profession: "Ingénieure géotechnicienne" },
    { metier: "Fondations", profession: "Ingénieure en fondations" },
    { metier: "Topographie", profession: "Ingénieure topographe ou topographe" },
    { metier: "Hydraulique", profession: "Ingénieure hydraulicienne" },
    { metier: "Génie rural", profession: "Ingénieure en génie rural" },
    { metier: "Génie urbain", profession: "Ingénieure en génie urbain" },
    { metier: "Architecture", profession: "Architecte" },
    { metier: "Urbanisme", profession: "Urbaniste" },
    { metier: "Aménagement du territoire", profession: "Spécialiste en aménagement du territoire" },
    { metier: "Conduite de travaux", profession: "Conductrice de travaux" },
    { metier: "Supervision de chantier", profession: "Superviseuse de chantier" },
    { metier: "Dessin technique", profession: "Dessinatrice technique" },
    { metier: "Dessin industriel", profession: "Dessinatrice industrielle" },
    { metier: "Conception assistée par ordinateur", profession: "Conceptrice CAO" },
    { metier: "Bureau d’études", profession: "Ingénieure d’études" },
    { metier: "Génie électrique", profession: "Ingénieure électricienne" },
    { metier: "Électrotechnique", profession: "Ingénieure électrotechnicienne" },
    { metier: "Électronique", profession: "Ingénieure électronicienne" },
    { metier: "Électronique de puissance", profession: "Ingénieure en électronique de puissance" },
    { metier: "Microélectronique", profession: "Ingénieure en microélectronique" },
    { metier: "Télécommunications", profession: "Ingénieure en télécommunications" },
    { metier: "Réseaux électriques", profession: "Ingénieure en réseaux électriques" },
    { metier: "Haute tension", profession: "Ingénieure haute tension" },
    { metier: "Automatique", profession: "Ingénieure automaticienne" },
    { metier: "Instrumentation", profession: "Ingénieure en instrumentation" },
    { metier: "Contrôle-commande", profession: "Ingénieure en contrôle-commande" },
    { metier: "Génie énergétique", profession: "Ingénieure énergéticienne" },
    { metier: "Énergies renouvelables", profession: "Ingénieure en énergies renouvelables" },
    { metier: "Énergie solaire", profession: "Ingénieure solaire" },
    { metier: "Énergie éolienne", profession: "Ingénieure en énergie éolienne" },
    { metier: "Hydroélectricité", profession: "Ingénieure hydroélectricienne" },
    { metier: "Géothermie", profession: "Ingénieure en géothermie" },
    { metier: "Biomasse-énergie", profession: "Ingénieure en biomasse-énergie" },
    { metier: "Bioénergie", profession: "Ingénieure en bioénergie" },
    { metier: "Hydrogène", profession: "Ingénieure hydrogène" },
    { metier: "Stockage d’énergie", profession: "Ingénieure en stockage d’énergie" },
    { metier: "Efficacité énergétique", profession: "Ingénieure en efficacité énergétique" },
    { metier: "Audit énergétique", profession: "Auditrice énergétique" },
    { metier: "Génie thermique", profession: "Ingénieure thermicienne" },
    { metier: "Thermodynamique appliquée", profession: "Ingénieure thermodynamicienne" },
    { metier: "Froid et climatisation", profession: "Ingénieure frigoriste" },
    { metier: "Génie mécanique", profession: "Ingénieure mécanicienne" },
    { metier: "Mécanique industrielle", profession: "Ingénieure en mécanique industrielle" },
    { metier: "Mécatronique", profession: "Ingénieure mécatronicienne" },
    { metier: "Robotique industrielle", profession: "Ingénieure en robotique industrielle" },
    { metier: "Maintenance industrielle", profession: "Ingénieure de maintenance industrielle" },
    { metier: "Fiabilité industrielle", profession: "Ingénieure fiabiliste" },
    { metier: "Génie automobile", profession: "Ingénieure automobile" },
    { metier: "Génie aéronautique", profession: "Ingénieure aéronautique" },
    { metier: "Génie aérospatial", profession: "Ingénieure aérospatiale" },
    { metier: "Génie naval", profession: "Ingénieure navale" },
    { metier: "Génie ferroviaire", profession: "Ingénieure ferroviaire" },
    { metier: "Génie industriel", profession: "Ingénieure industrielle" },
    { metier: "Production industrielle", profession: "Ingénieure de production" },
    { metier: "Méthodes industrielles", profession: "Ingénieure méthodes" },
    { metier: "Industrialisation", profession: "Ingénieure industrialisation" },
    { metier: "Qualité industrielle", profession: "Ingénieure qualité" },
    { metier: "Lean management", profession: "Ingénieure lean" },
    { metier: "Logistique industrielle", profession: "Ingénieure logistique" },
    { metier: "Chaîne d’approvisionnement", profession: "Ingénieure de la chaîne d’approvisionnement" },
    { metier: "Génie des procédés", profession: "Ingénieure des procédés" },
    { metier: "Génie chimique", profession: "Ingénieure chimiste" },
    { metier: "Génie pétrolier", profession: "Ingénieure pétrolière" },
    { metier: "Génie gazier", profession: "Ingénieure gazière" },
    { metier: "Raffinage", profession: "Ingénieure en raffinage" },
    { metier: "Pétrochimie", profession: "Ingénieure pétrochimiste" },
    { metier: "Génie minier", profession: "Ingénieure minière" },
    { metier: "Exploitation minière", profession: "Ingénieure d’exploitation minière" },
    { metier: "Métallurgie", profession: "Ingénieure métallurgiste" },
    { metier: "Science et génie des matériaux", profession: "Ingénieure des matériaux" },
    { metier: "Céramiques", profession: "Ingénieure céramiste" },
    { metier: "Polymères", profession: "Ingénieure en polymères" },
    { metier: "Génie textile", profession: "Ingénieure textile" },
    { metier: "Génie agroalimentaire", profession: "Ingénieure agroalimentaire" },
    { metier: "Génie agricole", profession: "Ingénieure agricole" },
    { metier: "Génie forestier", profession: "Ingénieure forestière" },
    { metier: "Génie environnemental", profession: "Ingénieure environnementale" },
    { metier: "Traitement des eaux", profession: "Ingénieure en traitement des eaux" },
    { metier: "Assainissement", profession: "Ingénieure en assainissement" },
    { metier: "Gestion des déchets", profession: "Ingénieure en gestion des déchets" },
    { metier: "Valorisation des déchets", profession: "Ingénieure en valorisation des déchets" },
    { metier: "Économie circulaire", profession: "Ingénieure en économie circulaire" },
    { metier: "Valorisation de la biomasse", profession: "Ingénieure en valorisation de la biomasse" },
    { metier: "Génie sanitaire", profession: "Ingénieure sanitaire" },
    { metier: "Génie biomédical", profession: "Ingénieure biomédicale" },
    { metier: "Dispositifs médicaux", profession: "Ingénieure en dispositifs médicaux" },
    { metier: "Génie pharmaceutique", profession: "Ingénieure pharmaceutique" },
    { metier: "Génie nucléaire", profession: "Ingénieure nucléaire" },
    { metier: "Radioprotection", profession: "Ingénieure en radioprotection" },
    { metier: "Sécurité industrielle", profession: "Ingénieure en sécurité industrielle" },
    { metier: "Hygiène, sécurité et environnement", profession: "Ingénieure HSE" },
    { metier: "Prévention des risques", profession: "Ingénieure en prévention des risques" },
    { metier: "Sûreté de fonctionnement", profession: "Ingénieure en sûreté de fonctionnement" },
    { metier: "Recherche et développement", profession: "Ingénieure en recherche et développement" },
    { metier: "Innovation industrielle", profession: "Ingénieure innovation" },
    { metier: "Gestion de projets techniques", profession: "Cheffe de projet technique" },
    { metier: "Direction technique", profession: "Directrice technique" },
    { metier: "Installation électrique", profession: "Installatrice-électricienne" },
    { metier: "Maintenance électrique", profession: "Technicienne de maintenance électrique" },
    { metier: "Maintenance aéronautique", profession: "Technicienne ou ingénieure de maintenance aéronautique" },
    { metier: "Soudage", profession: "Soudeuse" },
    { metier: "Usinage", profession: "Opératrice d’usinage" },
    { metier: "Chaudronnerie", profession: "Chaudronnière" },
    { metier: "Conduite de machines", profession: "Conductrice de machines industrielles" },
    { metier: "Technique de laboratoire industriel", profession: "Technicienne de laboratoire industriel" },
  ],
  mathematiques: [
    { metier: "Mathématiques", profession: "Mathématicienne" },
    { metier: "Mathématiques pures", profession: "Mathématicienne en mathématiques pures" },
    { metier: "Mathématiques appliquées", profession: "Mathématicienne appliquée" },
    { metier: "Algèbre", profession: "Algébriste" },
    { metier: "Géométrie", profession: "Géomètre mathématicienne" },
    { metier: "Topologie", profession: "Topologue" },
    { metier: "Analyse mathématique", profession: "Analyste mathématicienne" },
    { metier: "Analyse fonctionnelle", profession: "Mathématicienne en analyse fonctionnelle" },
    { metier: "Théorie des nombres", profession: "Spécialiste en théorie des nombres" },
    { metier: "Combinatoire", profession: "Combinatoricienne" },
    { metier: "Logique mathématique", profession: "Logicienne mathématique" },
    { metier: "Mathématiques discrètes", profession: "Mathématicienne en mathématiques discrètes" },
    { metier: "Probabilités", profession: "Probabiliste" },
    { metier: "Statistique", profession: "Statisticienne" },
    { metier: "Statistique appliquée", profession: "Statisticienne appliquée" },
    { metier: "Biostatistique", profession: "Biostatisticienne" },
    { metier: "Géostatistique", profession: "Géostatisticienne" },
    { metier: "Statistique publique", profession: "Statisticienne publique" },
    { metier: "Statistique agricole", profession: "Statisticienne agricole" },
    { metier: "Statistique sanitaire", profession: "Statisticienne de la santé" },
    { metier: "Statistique environnementale", profession: "Statisticienne environnementale" },
    { metier: "Démographie", profession: "Démographe" },
    { metier: "Économétrie", profession: "Économètre" },
    { metier: "Actuariat", profession: "Actuaire" },
    { metier: "Analyse de données", profession: "Analyste de données" },
    { metier: "Science des données", profession: "Scientifique des données" },
    { metier: "Modélisation mathématique", profession: "Modélisatrice mathématique" },
    { metier: "Modélisation statistique", profession: "Modélisatrice statistique" },
    { metier: "Simulation numérique", profession: "Spécialiste en simulation numérique" },
    { metier: "Calcul scientifique", profession: "Spécialiste en calcul scientifique" },
    { metier: "Analyse numérique", profession: "Analyste numérique" },
    { metier: "Recherche opérationnelle", profession: "Spécialiste en recherche opérationnelle" },
    { metier: "Optimisation", profession: "Spécialiste en optimisation" },
    { metier: "Aide à la décision", profession: "Analyste en aide à la décision" },
    { metier: "Algorithmique", profession: "Algorithmicienne" },
    { metier: "Cryptographie", profession: "Cryptographe" },
    { metier: "Cryptanalyse", profession: "Cryptanalyste" },
    { metier: "Mathématiques financières", profession: "Mathématicienne financière" },
    { metier: "Finance quantitative", profession: "Analyste quantitative" },
    { metier: "Ingénierie financière", profession: "Ingénieure financière" },
    { metier: "Analyse financière", profession: "Analyste financière" },
    { metier: "Gestion des risques", profession: "Analyste des risques" },
    { metier: "Risque bancaire", profession: "Analyste des risques bancaires" },
    { metier: "Risque assurantiel", profession: "Actuaire ou analyste des risques assurantiels" },
    { metier: "Prévision économique", profession: "Prévisionniste économique" },
    { metier: "Prévision statistique", profession: "Prévisionniste statisticienne" },
    { metier: "Études statistiques", profession: "Chargée d’études statistiques" },
    { metier: "Études économiques", profession: "Chargée d’études économiques" },
    { metier: "Études démographiques", profession: "Chargée d’études démographiques" },
    { metier: "Sondages", profession: "Spécialiste des sondages" },
    { metier: "Analyse de marché", profession: "Analyste de marché" },
    { metier: "Analyse décisionnelle", profession: "Analyste décisionnelle" },
    { metier: "Informatique décisionnelle", profession: "Analyste en informatique décisionnelle" },
    { metier: "Qualité des données", profession: "Analyste de la qualité des données" },
    { metier: "Gestion des données", profession: "Gestionnaire de données" },
    { metier: "Intelligence artificielle", profession: "Spécialiste en intelligence artificielle" },
    { metier: "Apprentissage automatique", profession: "Ingénieure en apprentissage automatique" },
    { metier: "Traitement du signal", profession: "Spécialiste en traitement du signal" },
    { metier: "Traitement d’images", profession: "Spécialiste en traitement d’images" },
    { metier: "Modélisation climatique", profession: "Modélisatrice climatique" },
    { metier: "Modélisation épidémiologique", profession: "Modélisatrice épidémiologique" },
    { metier: "Planification", profession: "Planificatrice" },
    { metier: "Suivi-évaluation", profession: "Spécialiste en suivi-évaluation" },
    { metier: "Évaluation de projets", profession: "Évaluatrice de projets" },
    { metier: "Analyse des politiques publiques", profession: "Analyste des politiques publiques" },
    { metier: "Enseignement des mathématiques", profession: "Enseignante de mathématiques" },
    { metier: "Recherche en mathématiques", profession: "Chercheuse en mathématiques" },
    { metier: "Recherche en statistique", profession: "Chercheuse en statistique" },
    { metier: "Médiation mathématique", profession: "Médiatrice scientifique en mathématiques" },
  ],
};
